{{- if .Values.web.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "temporal.componentname" (list . "web") }}
  labels:
    app.kubernetes.io/name: {{ include "temporal.name" . }}
    helm.sh/chart: {{ include "temporal.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: {{ .Chart.Name }}
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: {{ include "temporal.componentname" (list . "web") }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  wildcardPolicy: None
{{- end }}